load("@rules_ragel//ragel/internal:toolchain.bzl", "ragel_toolchain_alias")

toolchain_type(
    name = "toolchain_type",
    visibility = ["//visibility:public"],
)

ragel_toolchain_alias(
    name = "toolchain",
    visibility = ["//visibility:public"],
)
